In [1]:
import sys
sys.path.append('..')

In [2]:
import pandas as pd
from src.data_loader import load_raw_data
import src.features as features

In [3]:
games = load_raw_data("uefacompetitionresults.csv", sep=";")
games = features.get_score(games)
games[['Home', 'Away', 'Score', 'Date']].tail(10)

                    Home                   Away  Score        Date
28020  Slovan Bratislava              BK Häcken  1 - 0  2025-12-18
28021        AEK Larnaca       Shkëndija Tetovo  1 - 0  2025-12-18
28022           NK Celje             Shelbourne  0 - 0  2025-12-18
28023    1. FSV Mainz 05             Samsunspor  2 - 0  2025-12-18
28024    Lausanne Sports             Fiorentina  1 - 0  2025-12-18
28025       Sparta Praha               Aberdeen  3 - 0  2025-12-18
28026   Shakhtar Donetsk                 Rijeka  0 - 0  2025-12-18
28027     Crystal Palace            KuPS Kuopio  2 - 2  2025-12-18
28028    Zrinjski Mostar             Rapid Wien  1 - 1  2025-12-18
28029         AZ Alkmaar  Jagiellonia Białystok  0 - 0  2025-12-18

In [4]:
games = features.match_result(games)
games.head()

,Date,Season,Cup,Round,Home,Away,gh,ga,HomeCountry,AwayCountry,gh1h,ga1h,IsWalkover,Score,Winner
0,1955-06-04,1955/1958,ICF,Group stage,Basel XI,London XI,0,5,Switzerland,England,0,3,0,0 - 5,London XI
1,1955-09-04,1955/1956,EC,1/8 Final,Sporting CP,Partizan Beograd,3,3,Portugal,Serbia,1,1,0,3 - 3,Draw
2,1955-09-07,1955/1956,EC,1/8 Final,MTK Budapest,Anderlecht,6,3,Hungary,Belgium,3,2,0,6 - 3,MTK Budapest
3,1955-09-08,1955/1956,EC,1/8 Final,Servette,Real Madrid,0,2,Switzerland,Spain,0,0,0,0 - 2,Real Madrid
4,1955-09-14,1955/1956,EC,1/8 Final,Rot-Weiß Erfurt,Hibernian,0,4,East Germany,Scotland,0,1,0,0 - 4,Hibernian

In [ ]:
games = features.format_date(games)
games[['Home', 'Away', 'Score','Date']].head(10)

               Home              Away  Score      Date
0          Basel XI         London XI  0 - 5    6/4/55
1       Sporting CP  Partizan Beograd  3 - 3    9/4/55
2      MTK Budapest        Anderlecht  6 - 3    9/7/55
3          Servette       Real Madrid  0 - 2    9/8/55
4   Rot-Weiß Erfurt         Hibernian  0 - 4   9/14/55
5    Djurgårdens IF  Gwardia Warszawa  0 - 0   9/20/55
6         Aarhus GF       Stade Reims  0 - 2   9/21/55
7        Rapid Wien     PSV Eindhoven  6 - 1   9/21/55
8       Real Madrid          Servette  5 - 0  10/12/55
9  Partizan Beograd       Sporting CP  5 - 2  10/12/55