In [5]:
import sys
sys.path.append('..')

In [6]:
import pandas as pd
from src.data_loader import load_raw_data
import src.features as features

In [7]:
games = load_raw_data("uefacompetitionresults.csv", sep=";")
games = features.get_score(games)
games[['Home', 'Away', 'Score', 'Date']].tail(10)

                    Home                   Away  Score        Date
28020  Slovan Bratislava              BK Häcken  1 - 0  2025-12-18
28021        AEK Larnaca       Shkëndija Tetovo  1 - 0  2025-12-18
28022           NK Celje             Shelbourne  0 - 0  2025-12-18
28023    1. FSV Mainz 05             Samsunspor  2 - 0  2025-12-18
28024    Lausanne Sports             Fiorentina  1 - 0  2025-12-18
28025       Sparta Praha               Aberdeen  3 - 0  2025-12-18
28026   Shakhtar Donetsk                 Rijeka  0 - 0  2025-12-18
28027     Crystal Palace            KuPS Kuopio  2 - 2  2025-12-18
28028    Zrinjski Mostar             Rapid Wien  1 - 1  2025-12-18
28029         AZ Alkmaar  Jagiellonia Białystok  0 - 0  2025-12-18

In [8]:
games = features.match_result(games)
games.head()

,Date,Season,Cup,Round,Home,Away,gh,ga,HomeCountry,AwayCountry,gh1h,ga1h,IsWalkover,Score,Winner
0,1955-06-04,1955/1958,ICF,Group stage,Basel XI,London XI,0,5,Switzerland,England,0,3,0,0 - 5,London XI
1,1955-09-04,1955/1956,EC,1/8 Final,Sporting CP,Partizan Beograd,3,3,Portugal,Serbia,1,1,0,3 - 3,Draw
2,1955-09-07,1955/1956,EC,1/8 Final,MTK Budapest,Anderlecht,6,3,Hungary,Belgium,3,2,0,6 - 3,MTK Budapest
3,1955-09-08,1955/1956,EC,1/8 Final,Servette,Real Madrid,0,2,Switzerland,Spain,0,0,0,0 - 2,Real Madrid
4,1955-09-14,1955/1956,EC,1/8 Final,Rot-Weiß Erfurt,Hibernian,0,4,East Germany,Scotland,0,1,0,0 - 4,Hibernian

In [12]:
champions = games[games['Cup']=='CL']
champions.tail(30)

,Date,Season,Cup,Round,Home,Away,gh,ga,HomeCountry,AwayCountry,gh1h,ga1h,IsWalkover,Score,Winner
27910,2025-11-25,2025/2026,CL,League phase,Napoli,Qarabağ Ağdam,2,0,Italy,Azerbaijan,0,0,0,2 - 0,Napoli
27911,2025-11-25,2025/2026,CL,League phase,Borussia Dortmund,Villarreal,4,0,Germany,Spain,1,0,0,4 - 0,Borussia Dortmund
27912,2025-11-25,2025/2026,CL,League phase,Chelsea,FC Barcelona,3,0,England,Spain,1,0,0,3 - 0,Chelsea
27913,2025-11-26,2025/2026,CL,League phase,Eintracht Frankfurt,Atalanta,0,3,Germany,Italy,0,0,0,0 - 3,Atalanta
27914,2025-11-26,2025/2026,CL,League phase,København,Kairat Almaty,3,2,Denmark,Kazakhstan,1,0,0,3 - 2,København
27915,2025-11-26,2025/2026,CL,League phase,Sporting CP,Club Brugge,3,0,Portugal,Belgium,2,0,0,3 - 0,Sporting CP
27916,2025-11-26,2025/2026,CL,League phase,Atlético Madrid,Inter Milan,2,1,Spain,Italy,1,0,0,2 - 1,Atlético Madrid
27917,2025-11-26,2025/2026,CL,League phase,Arsenal,Bayern München,3,1,England,Germany,1,1,0,3 - 1,Arsenal
27918,2025-11-26,2025/2026,CL,League phase,Olympiacos,Real Madrid,3,4,Greece,Spain,1,3,0,3 - 4,Real Madrid
27919,2025-11-26,2025/2026,CL,League phase,Paris Saint-Germain,Tottenham Hotspur,5,3,France,England,1,1,0,5 - 3,Paris Saint-Germain
27920,2025-11-26,2025/2026,CL,League phase,Pafos,Monaco,2,2,Cyprus,France,1,2,0,2 - 2,Draw
27921,2025-11-26,2025/2026,CL,League phase,Liverpool,PSV Eindhoven,1,4,England,Netherlands,1,1,0,1 - 4,PSV Eindhoven
27958,2025-12-09,2025/2026,CL,League phase,Tottenham Hotspur,Slavia Praha,3,0,England,Czech Republic,1,0,0,3 - 0,Tottenham Hotspur
27959,2025-12-09,2025/2026,CL,League phase,Monaco,Galatasaray,1,0,France,Turkey,0,0,0,1 - 0,Monaco
27960,2025-12-09,2025/2026,CL,League phase,Union Saint-Gilloise,Olympique Marseille,2,3,Belgium,France,1,2,0,2 - 3,Olympique Marseille
27961,2025-12-09,2025/2026,CL,League phase,FC Barcelona,Eintracht Frankfurt,2,1,Spain,Germany,0,1,0,2 - 1,FC Barcelona
27962,2025-12-09,2025/2026,CL,League phase,Atalanta,Chelsea,2,1,Italy,England,0,1,0,2 - 1,Atalanta
27963,2025-12-09,2025/2026,CL,League phase,Bayern München,Sporting CP,3,1,Germany,Portugal,0,0,0,3 - 1,Bayern München
27964,2025-12-09,2025/2026,CL,League phase,Inter Milan,Liverpool,0,1,Italy,England,0,0,0,0 - 1,Liverpool
27965,2025-12-09,2025/2026,CL,League phase,Kairat Almaty,Olympiacos,0,1,Kazakhstan,Greece,0,0,0,0 - 1,Olympiacos
27966,2025-12-09,2025/2026,CL,League phase,PSV Eindhoven,Atlético Madrid,2,3,Netherlands,Spain,1,1,0,2 - 3,Atlético Madrid
27967,2025-12-10,2025/2026,CL,League phase,Villarreal,København,2,3,Spain,Denmark,0,1,0,2 - 3,København
27968,2025-12-10,2025/2026,CL,League phase,Athletic Bilbao,Paris Saint-Germain,0,0,Spain,France,0,0,0,0 - 0,Draw
27969,2025-12-10,2025/2026,CL,League phase,Bayer Leverkusen,Newcastle United,2,2,Germany,England,1,0,0,2 - 2,Draw
27970,2025-12-10,2025/2026,CL,League phase,Real Madrid,Manchester City,1,2,Spain,England,1,2,0,1 - 2,Manchester City
27971,2025-12-10,2025/2026,CL,League phase,Juventus,Pafos,2,0,Italy,Cyprus,0,0,0,2 - 0,Juventus
27972,2025-12-10,2025/2026,CL,League phase,Benfica,Napoli,2,0,Portugal,Italy,1,0,0,2 - 0,Benfica
27973,2025-12-10,2025/2026,CL,League phase,Borussia Dortmund,Bodø/Glimt,2,2,Germany,Norway,1,1,0,2 - 2,Draw
27974,2025-12-10,2025/2026,CL,League phase,Club Brugge,Arsenal,0,3,Belgium,England,0,1,0,0 - 3,Arsenal
27975,2025-12-10,2025/2026,CL,League phase,Qarabağ Ağdam,Ajax,2,4,Azerbaijan,Netherlands,1,1,0,2 - 4,Ajax